/*
 * generated by Xtext 2.12.0
 */
package tmodel.grm.trm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTrmScopeProvider extends DelegatingScopeProvider {
}
