/*
 * generated by Xtext 2.12.0
 */
package tmodel.grm.trm.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class TrmProposalProvider extends AbstractTrmProposalProvider {
}
