/*
 * generated by Xtext 2.12.0
 */
package tmodel.grm.trm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import tmodel.grm.trm.TrmRuntimeModule;
import tmodel.grm.trm.TrmStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TrmIdeSetup extends TrmStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TrmRuntimeModule(), new TrmIdeModule()));
	}
	
}
