<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tmodel" nsURI="http://transformermodel.com" nsPrefix="tmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Runner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loader" lowerBound="2"
        upperBound="2" eType="#//Loader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" lowerBound="1"
        upperBound="-1" eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loader" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadMetaModel" eSuperTypes="#//Loader"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoadModel" eSuperTypes="#//Loader"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cibleElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//MAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereClause" eType="#//WhereClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Add" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Update" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delete" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="MElement" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//MAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAttribute" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
        upperBound="-1" eType="#//MAttribute" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
