/*
 * generated by Xtext 2.12.0
 */
package tmodel.grm.trm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TrmUiModule extends AbstractTrmUiModule {

	public TrmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
