/*
 * generated by Xtext 2.12.0
 */
package tmodel.grm.trm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TrmAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tmodel/grm/trm/parser/antlr/internal/InternalTrm.tokens");
	}
}
