/*
 * generated by Xtext 2.12.0
 */
package tmodel.grm.trm.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tmodel.grm.trm.parser.antlr.internal.InternalTrmParser;
import tmodel.grm.trm.services.TrmGrammarAccess;

public class TrmParser extends AbstractAntlrParser {

	@Inject
	private TrmGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTrmParser createParser(XtextTokenStream stream) {
		return new InternalTrmParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Runner";
	}

	public TrmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TrmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
