/*
 * generated by Xtext 2.12.0
 */
package tmodel.grm.trm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TrmStandaloneSetup extends TrmStandaloneSetupGenerated {

	public static void doSetup() {
		new TrmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
