/**
 *
 * $Id$
 */
package SimplStateMachineDC.validation;

import SimplStateMachineDC.CompositeState;

/**
 * A sample validator interface for {@link SimplStateMachineDC.State}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateContainer(CompositeState value);
	boolean validateIsActive(boolean value);
	boolean validateOrd(String value);
	boolean validateInh(String value);
	boolean validateOrdIf(String value);
	boolean validateInhIf(String value);
}
