/*
 * generated by Xtext 2.12.0
 */
package tmodel.grm.trm.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tmodel.grm.ui.internal.GrmActivator;

public class TrmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GrmActivator.getInstance().getInjector("tmodel.grm.trm.Trm");
	}

}
